def wrap(s):
    return s.replace("  ", "")


SUB_QUERY_GENERATION = wrap("""
        You are using a search engine to answer the main query by iteratively searching the web. Given the following intermediate queries and answers, generate a new simple follow-up question that can help answer the main query. You may rephrase or decompose the main query when previous answers are not helpful. Ask simple follow-up questions only as the search engine may not understand complex questions.
        ## Previous intermediate queries and answers
        {intermediate queries and answers}
        ## Task description
        {task description}
        ## Main query to answer
        {query}
        Respond with a simple follow-up question that will help answer the main query, do not explain yourself or output anything else.
        """)

INTER_ANS_GENERATION = wrap("""
        Given the following documents, generate an appropriate answer for the query. DO NOT hallucinate any information, only use the provided documents to generate the answer. Respond “No relevant information found” if the documents do not contain useful information.
        ## Documents
        {retrieved documents}
        ## Query
        {sub-query}
        Respond with a concise answer only, do not explain yourself or output anything else.
        """)

FINAL_ANS_GENERATION = wrap("""
        Given the following intermediate queries and answers, generate a final answer for the main query by combining relevant information. Note that intermediate answers are generated by an LLM and may not always be accurate.
        ## Documents
        {retrieved documents}
        ## Intermediate queries and answers
        {intermediate queries and answers}
        ## Task description
        {task description}
        ## Main query
        {query}
        Respond with an appropriate answer only, do not explain yourself or output anything else.
        """)

LEARNING_TO_STOP = wrap("""     
        Given the following intermediate queries and answers, judge whether you have enough information to answer the main query. If you believe you have enough information, respond with “Yes”, otherwise respond with
        “No”.
        ## Intermediate queries and answers
        {intermediate queries and answers}
        ## Main query
        {query}
        Respond with “Yes” or “No” only, do not explain yourself or output anything else.
        """)